core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Polo tisort'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Categories(models.Model):
    categoriTitle = models.CharField(max_length=100)
    def __str__(self):
        return self.categoriTitle 
    
class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    Categories = models.ForeignKey(
        'Categories', related_name='title', on_delete=models.SET_NULL, blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
  <!--Copyright-->
  <div class="footer-copyright py-3">
    <p style="text-align: center;">İleri Web Ödevi</p>
  </div>
  <!--/.Copyright-->
</footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
<main>
  <div style="margin-top: 7rem;" class="container">
    <div style="position: relative; top:200px" class="mt-5"></div>

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <div class="row">
        <div class="col-3">
          <select class="form-control" id="sorting">
            <option value="bos">Sıralama Yap</option>
            <option value="price">Artan Fiyat</option>
            <option value="-price">Azalan Fiyat</option>
          </select>
        </div>
        <div class="col-9">
          <div class="card">
            <div class="card-header">
              <form class="theme-form">
                <div class="input-group m-0 flex-nowrap">
                  <input id="searchbarurun" class="form-control-plaintext" type="search"
                    placeholder="Arama yapmak istediğiniz ürünü giriniz">
                </div>
              </form>
            </div>
          </div>
        </div>

      </div>
      <div class="row wow fadeIn">
        <div class="row" id="item-container">
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                  class="card-img-top" {% endcomment %} <img height="200" src="{{ item.image.url }}"
                  class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.Categories }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}₺
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('searchbarurun');
    const itemContainer = document.getElementById('item-container');

    searchInput.addEventListener('input', function () {
      const searchText = searchInput.value.toLowerCase().trim();
      const items = document.querySelectorAll('.col-lg-3');

      items.forEach(function (item) {
        const titleElement = item.querySelector('.dark-grey-text');

        // Eğer başlık içinde aranan metin bulunuyorsa display'i inline block yap, yoksa none yap
        if (titleElement.textContent.toLowerCase().includes(searchText)) {
          item.style.display = 'inline-block';
        } else {
          item.style.display = 'none';
        }
      });
    });
  });
</script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const sortingSelect = document.getElementById('sorting');
    const itemContainer = document.getElementById('item-container');

    sortingSelect.addEventListener('change', function () {
      const selectedValue = sortingSelect.value;

      // AJAX veya başka bir yöntemle sıralama işlemini gerçekleştirin
      // Bu örnekte sadece öğeleri yeniden sıralayarak simüle ediyoruz
      const items = document.querySelectorAll('.col-lg-3');
      const sortedItems = Array.from(items).sort(function (a, b) {
        const priceA = parseFloat(a.querySelector('.font-weight-bold strong').textContent);
        const priceB = parseFloat(b.querySelector('.font-weight-bold strong').textContent);

        return selectedValue === 'price' ? priceA - priceB : priceB - priceA;
      });

      // Yeniden sıralanmış öğeleri container içine ekleyin
      itemContainer.innerHTML = '';
      sortedItems.forEach(function (item) {
        itemContainer.appendChild(item);
      });
    });
  });
</script>
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="/">
      <strong class="blue-text">IW Donem Odevı</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> {% endcomment %}
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Sepet </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Çıkış </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Giriş </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Kayıt </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>
<div style="height: 7rem;    background-color: #F4F7F9;
"></div>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Sepetin</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        {% if order.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Kupon</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Toplam Tutar</span>
            <strong>{{ order.get_total }}₺</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Onayla</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2>Kullanıcı Sepeti</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Ürün Adı</th>
                        <th scope="col">Fiyatı</th>
                        <th scope="col">Adet</th>
                        <th scope="col">Fiyat</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.title }}</td>
                        <td>{{ order_item.item.price }}</td>
                        <td>
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2"></i>-</a>
                            {{ order_item.quantity }}
                            <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2"></i>+</a>
                        </td>
                        <td>
                            {% if order_item.item.discount_price %}
                            {{ order_item.get_total_discount_item_price }}₺
                            <span class="badge badge-primary">Kazancınız {{ order_item.get_amount_saved }}₺</span>
                            {% else %}
                            {{ order_item.get_total_item_price }}₺
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Sepetinizde ürün yok!</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-primary float-right' href='/'>
                                Alışverişe devam et
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Kupon Kazancı</b></td>
                        <td><b>-{{ object.coupon.amount }}₺</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Sepet tutarı</b></td>
                        <td><b>{{ object.get_total }}₺</b></td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Sepeti Onayla</a>
                            <a class='btn btn-primary float-right' href='/'>Alışverişe devam et</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>

    </div>
</main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description"
    content="Mofi admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
  <meta name="keywords"
    content="admin template, Mofi admin template, dashboard template, flat admin template, responsive admin template, web app">
  <meta name="author" content="pixelstrap">
  <link rel="icon" href="../assets/images/favicon.png" type="image/x-icon">
  <link rel="shortcut icon" href="../assets/images/favicon.png" type="image/x-icon">
  <title>Mofi - Premium Admin Template</title>
  <!-- Google font-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&amp;display=swap"
    rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="../assets/css/font-awesome.css">
  <!-- ico-font-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/icofont.css">
  <!-- Themify icon-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/themify.css">
  <!-- Flag icon-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/flag-icon.css">
  <!-- Feather icon-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/feather-icon.css">
  <!-- Plugins css start-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/slick-theme.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/scrollbar.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/animate.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/select2.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/owlcarousel.css">
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/range-slider.css">
  <!-- Plugins css Ends-->
  <!-- Bootstrap css-->
  <link rel="stylesheet" type="text/css" href="../assets/css/vendors/bootstrap.css">
  <!-- App css-->
  <link rel="stylesheet" type="text/css" href="../assets/css/style.css">
  <link id="color" rel="stylesheet" href="../assets/css/color-1.css" media="screen">
  <!-- Responsive css-->
  <link rel="stylesheet" type="text/css" href="../assets/css/responsive.css">
</head>

<body>
  <div class="tap-top"><i data-feather="chevrons-up"></i></div>
  <!-- tap on tap ends-->
  <!-- page-wrapper Start-->
  <div style="    background-color: #F4F7F9;
  " class="page-wrapper compact-wrapper" id="pageWrapper">
    <!-- Page Body Start-->
    <div class="page-body-wrapper">
      <div class="page-body">
        <!-- Container-fluid starts-->
        <div class="container-fluid">
          <div>
            <div class="row product-page-main p-0">
              <div class="col-xxl-4 col-md-6 box-col-6">
                <div class="card">
                  <div class="card-body">
                    <div id="sync1">
                      <div class="item"><img height="300" style='width:100%' src="../../media/{{ object.image }}"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xxl-5 box-col-6 order-xxl-0 order-1">
                <div class="card">
                  <div class="card-body">
                    <div class="product-page-details">
                      <h3 class="f-w-600">{{ object.title }}</h3>
                    </div>
                    <div class="product-price">{{ object.discount_price }}₺
                      <del>{{ object.price }}₺ </del>
                    </div>
                    <hr>
                    <p>{{ object.description }}</p>
                    <hr>
                    <div>
                      <table class="product-page-width">
                        <tbody>
                          <tr>
                            <td> <b>Etiketler &nbsp;&nbsp;&nbsp;: &nbsp;&nbsp;&nbsp;</b></td>
                            <td>{{ object.slug }}</td>
                          </tr>
                          <tr>
                            <td> <b>Kategori &nbsp;&nbsp;&nbsp;: &nbsp;&nbsp;&nbsp;</b></td>
                            <td>{{ item.get_category_display }}</td>

                          </tr>
                        </tbody>
                      </table>
                    </div>
                    <hr>
                    <div class="m-t-15 btn-showcase"><a class="btn btn-primary" href="{{ object.get_add_to_cart_url }}"
                        title=""> <i class="fa fa-shopping-basket me-1"></i>Sepete Ekle</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Container-fluid Ends-->
      </div>
      <!-- footer start-->
      <footer class="footer">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12 footer-copyright d-flex flex-wrap align-items-center justify-content-between">
              <p class="mb-0 f-w-600">Copyright 2023 © Mofi theme by pixelstrap </p>
              <p class="mb-0 f-w-600">Hand crafted & made with
                <svg class="footer-icon">
                  <use href="../assets/svg/icon-sprite.svg#footer-heart"> </use>
                </svg>
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- latest jquery-->
  <script src="../assets/js/jquery.min.js"></script>
  <!-- Bootstrap js-->
  <script src="../assets/js/bootstrap/bootstrap.bundle.min.js"></script>
  <!-- feather icon js-->
  <script src="../assets/js/icons/feather-icon/feather.min.js"></script>
  <script src="../assets/js/icons/feather-icon/feather-icon.js"></script>
  <!-- scrollbar js-->
  <script src="../assets/js/scrollbar/simplebar.js"></script>
  <script src="../assets/js/scrollbar/custom.js"></script>
  <!-- Sidebar jquery-->
  <script src="../assets/js/config.js"></script>
  <!-- Plugins JS start-->
  <script src="../assets/js/sidebar-menu.js"></script>
  <script src="../assets/js/sidebar-pin.js"></script>
  <script src="../assets/js/slick/slick.min.js"></script>
  <script src="../assets/js/slick/slick.js"></script>
  <script src="../assets/js/header-slick.js"></script>
  <!-- calendar js-->
  <script src="../assets/js/range-slider/ion.rangeSlider.min.js"></script>
  <script src="../assets/js/range-slider/rangeslider-script.js"></script>
  <script src="../assets/js/touchspin/vendors.min.js"></script>
  <script src="../assets/js/touchspin/touchspin.js"></script>
  <script src="../assets/js/touchspin/input-groups.min.js"></script>
  <script src="../assets/js/owlcarousel/owl.carousel.js"></script>
  <script src="../assets/js/select2/select2.full.min.js"></script>
  <script src="../assets/js/select2/select2-custom.js"></script>
  <script src="../assets/js/product-tab.js"></script>
  <!-- Plugins JS Ends-->
  <!-- Theme js-->
  <script src="../assets/js/script.js"></script>
  <script src="../assets/js/theme-customizer/customizer.js"></script>
  <!-- Plugin used-->
</body>

</html>
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>